In [1]:
import matplotlib.pyplot as plt
from glob import glob
import pandas as pd 
import numpy as np 
from pickle import load, dump
import datetime as dt 
import sys
sys.path.append('/Users/jerald/Documents/Dir/Python/Stocks')
from bin.main import Manager 
m = Manager('../../../')
e = m.Earningsdb.get_earning_dates()

Options db Connected: 2024-09-22 19:20:29.918108
Prices Connected: 2024-09-22 19:20:29.919064

In [2]:
dt.datetime.now().date()

datetime.date(2024, 9, 22)

In [4]:
m.Earningsdb.common_balance_sheet_change().sort_values('Tangible Book Value', ascending=False)

,lastEarningsDate,Total Equity Gross Minority Interest,Share Issued,Total Debt,Total Liabilities Net Minority Interest,Net Tangible Assets,Tangible Book Value,Retained Earnings,Invested Capital,Capital Stock,Common Stock,Cash And Cash Equivalents,Common Stock Equity,Ordinary Shares Number,Total Capitalization,Total Assets,Stockholders Equity
stock,,,,,,,,,,,,,,,,,
HD,2024-07-31,142.857143,0.055617,26.662877,19.398011,264.358820,264.358820,2.740306,34.722627,0.000000,0.000000,-62.171670,142.857143,0.100806,28.279398,22.234002,142.857143
MRK,2024-06-30,7.975460,0.000000,10.429878,5.436760,237.492241,237.492241,6.155529,9.099929,0.000000,0.000000,102.616956,7.972451,0.116421,9.499902,6.406296,7.972451
GME,2024-07-31,227.461527,39.515865,-11.496350,-15.871278,227.461527,227.461527,8.223684,222.346573,100.000000,100.000000,354.931106,227.461527,39.515865,224.102337,104.366925,227.461527
PANW,2024-07-31,15.710193,0.525665,-12.262612,10.088390,110.138182,110.138182,36.040302,8.939133,8.224998,8.224998,11.756570,15.710193,0.525665,15.710193,11.489169,15.710193
UBER,2024-06-30,10.272822,0.561007,-0.152316,2.328413,83.720930,83.720930,-3.248208,6.283207,NaN,NaN,-10.400478,11.683849,0.561007,6.283207,4.835981,11.683849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
EBAY,2024-06-30,-11.924119,0.230282,-0.377680,-1.928029,-39.156035,-39.156035,0.271547,-5.343621,0.000000,0.000000,-7.840376,-11.924119,-2.946955,-6.009480,-4.855729,-11.924119
CHGG,2024-06-30,-62.064363,1.763022,-0.052688,-2.644409,-43.156620,-43.156620,1146.773744,-38.202744,0.980392,0.980392,-7.429025,-62.064363,1.763022,-49.553835,-35.686154,-62.064363
RBLX,2024-06-30,77.550369,1.074922,1.466962,1.715152,-46.362407,-46.362407,6.181082,4.665631,0.000000,0.000000,11.540903,69.698747,1.074922,4.665631,2.467983,69.698747
GE,2024-06-30,-39.417420,-0.940581,-4.151035,-21.448520,-51.426754,-51.426754,-12.168285,-24.035331,0.000000,0.000000,-34.368732,-37.705577,-0.940581,-25.893653,-24.857572,-37.705577
MMM,2024-06-30,-19.156700,0.000000,-38.191091,-21.707414,-69.555113,-69.555113,-5.329313,-35.313368,0.000000,0.000000,-7.588672,-19.523222,-0.724235,-38.344004,-21.479644,-19.523222

In [5]:
m.Earningsdb.upcoming_earnings(n = 0)

Empty DataFrame
Columns: [stock, Date, Hour, Time, EPS, Reported EPS, Surprise(%)]
Index: []