In [19]:
import json 
import pandas as pd 
import numpy as np 
import sqlite3 as sql 

stock_db = sql.connect('../../data/stocks/stock_names.db')
stock_info = json.load(open('../stock_info_all.json', 'r'))
stocks = list(stock_info.keys())
len(stocks)

174

In [20]:
# len(list(stock_info['gdx'].keys()))
# sorted([x for x in stock_info['sony'].keys()])

In [21]:
# stock_info['sony']['currency']

In [15]:
lodf = []; error = []
for x in stocks: 
    try:
        dm = pd.DataFrame(stock_info[x])
        if 'companyOfficers' in dm.columns: 
            dm.drop(columns = ['companyOfficers']) 
        lodf.append(dm)
    except:
        error.append(x)
        
lodf2 = [pd.DataFrame(x.iloc[0]).T for x in lodf]
df = pd.concat(lodf2).reset_index(drop=True)
df.columns = [x.lower() for x in df.columns]

df.beta = df.beta.astype(float) 
df.forwardpe = df.forwardpe.astype(float)
df.columns

Index(['address1', 'city', 'state', 'zip', 'country', 'phone', 'website',
       'industry', 'industrykey', 'industrydisp',
       ...
       'date', 'earningsquarterlygrowth', 'earningsgrowth', 'dividendrate',
       'dividendyield', 'payoutratio', 'trailingannualdividendrate',
       'trailingannualdividendyield', 'address2', 'fax'],
      dtype='object', length=135)

In [16]:
lodf_etf = []; error2 = []

for i in error:
    try:
        dm = pd.DataFrame(stock_info[i], index = [i])
        lodf_etf.append(dm)
    except:
        error2.append(i)
        
lodf_etf2 = [pd.DataFrame(x.iloc[0]).T for x in lodf_etf]
df_etf = pd.concat(lodf_etf2).reset_index(drop=False).rename(columns = {'index':'stock'})
df_etf.columns

Index(['stock', 'phone', 'longBusinessSummary', 'maxAge', 'priceHint',
       'previousClose', 'open', 'dayLow', 'dayHigh',
       'regularMarketPreviousClose', 'regularMarketOpen',
       'regularMarketDayLow', 'regularMarketDayHigh', 'trailingPE', 'volume',
       'regularMarketVolume', 'averageVolume', 'averageVolume10days',
       'averageDailyVolume10Day', 'bid', 'ask', 'bidSize', 'askSize', 'yield',
       'totalAssets', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'fiftyDayAverage',
       'twoHundredDayAverage', 'navPrice', 'currency', 'category', 'ytdReturn',
       'beta3Year', 'fundFamily', 'fundInceptionDate', 'legalType',
       'threeYearAverageReturn', 'fiveYearAverageReturn', 'exchange',
       'quoteType', 'symbol', 'underlyingSymbol', 'shortName', 'longName',
       'firstTradeDateEpochUtc', 'timeZoneFullName', 'timeZoneShortName',
       'uuid', 'messageBoardId', 'gmtOffSetMilliseconds', 'trailingPegRatio',
       'date', 'trailingAnnualDividendRate', 'trailingAnnualDividendYield',
       'forwardPE'],
      dtype='object')

In [6]:
c = ['industry', 'sector', 'industrykey', 'sectorkey']

ind_sect = df.set_index('symbol').sort_values('sector', ascending=True)[c].reset_index().copy()

#### Write the Industry and Sector to the stock Database
# ind_sect.to_sql('sectors', stock_db, if_exists='replace', index=False)

Price-to-book Ratio: $$ \frac{ \text{MarketCap}}{\text{BookValue of Equity}} $$
Book Value Of Equity: $$ \text

In [7]:
c = [
    'pricetobook', 'marketcap', 'sharesoutstanding','enterprisevalue', 'floatshares', 
    'dividendyield', 'forwardpe', 'marketcap', 'profitmargins', 
     'grossmargins', 'operatingmargins', 'ebitda', 
     'totalrevenue', 'debttoequity', 'returnonassets' ,'returnonequity',
     'freecashflow', 'operatingcashflow', 'trailingpegratio', 'overallrisk',
     ]
cry = (df.marketcap > 4e9)

df[cry].set_index('symbol').sort_values('pricetobook', ascending=True).head(20)[c]

,pricetobook,marketcap,sharesoutstanding,enterprisevalue,floatshares,dividendyield,forwardpe,marketcap,profitmargins,grossmargins,operatingmargins,ebitda,totalrevenue,debttoequity,returnonassets,returnonequity,freecashflow,operatingcashflow,trailingpegratio,overallrisk
symbol,,,,,,,,,,,,,,,,,,,,
SONY,0.014158,110909546496,1214050048,3727386476544,1178832616,0.0063,15.563033,110909546496,0.07534,0.26298,0.09211,1593363005440,13068765495296,51.21,0.02244,0.13113,1976963956736,1259596939264,4.1038,1
BABA,0.213355,199965245440,2376009984,1488949346304,15575709760,0.024,8.658446,199965245440,0.07383,0.37902,0.16089,176592994304,950248013824,22.796,0.04679,0.05668,142874492928,170922999808,3.7057,NaN
VALE,0.219416,45448986624,4269829888,112752500736,3984538964,0.1743,4.733184,45448986624,0.23194,0.40662,0.30082,84191002624,210092998656,45.818,0.09439,0.24047,37548748800,61641998336,None,1
LI,0.346575,21740998656,883104000,-42360954880,1090553571,NaN,12.304598,21740998656,0.08697,0.22151,-0.02282,8320204288,130697936896,24.778,0.03292,0.21151,29813819392,39570767872,1.1312,NaN
C,0.617246,117406015488,1907800064,-179882377216,1846001738,0.035,8.655415,117406015488,0.11892,NaN,0.24436,NaN,69750996992,NaN,0.0035,0.04037,NaN,-16663000064,0.9952,1
WBA,0.69259,9448544256,863275008,44167962624,714403257,0.0916,5.391625,9448544256,-0.03993,0.18378,0.00297,3953999872,145532993536,218.172,0.01296,-0.55966,2168375040,725000000,None,7
MOS,0.769231,8956914688,318638016,13024434176,316901007,0.0303,11.244000,8956914688,0.02008,0.14452,0.08283,1936600064,12193800192,36.891,0.02271,0.02269,218250000,1952499968,1.694,3
INTC,0.793194,91399503872,4276000000,118201122816,4269243920,0.024,18.915930,91399503872,0.01769,0.41416,-0.07956,10588999680,55120998400,44.032,0.00162,0.00782,-10409249792,11516999680,1.9817,4
X,0.806579,9189697536,224962000,11801157632,202580435,0.0048,13.616666,9189697536,0.034,0.11416,0.04395,1450000000,16853000192,37.768,0.01694,0.05138,-1055750016,1652000000,None,1
RUN,0.835206,4486447616,223540000,17515425792,206396432,NaN,-27.874998,4486447616,-0.66365,0.10027,-0.24443,-113393000,2061825024,173.815,-0.02081,-0.33449,-2458684416,-530884992,None,7
NTR,0.936171,23525695488,494756992,35542740992,494287137,0.0462,11.977329,23525695488,0.03057,0.30357,0.15752,4680000000,25838999552,53.142,0.03274,0.0322,2029874944,5000999936,None,3
F,0.976734,42555052032,3904399872,168266874880,3890497362,0.0571,5.604712,42555052032,0.02127,0.08038,0.04309,10570000384,180347994112,350.717,0.00993,0.08754,-1228125056,13976000512,0.5795,10
CVS,0.986289,74019545088,1257980032,141144096768,1254708524,0.0456,8.016349,74019545088,0.01987,0.14372,0.03031,16135999488,361854992384,111.598,0.02882,0.09728,5598875136,8072000000,2.0135,5
AIG,1.089325,47974346752,643950976,43398066176,641626769,0.0218,10.582386,47974346752,-0.01396,0.28592,0.14224,9004000256,45924999168,22.35,0.00898,0.08733,19389874176,6581000192,1.0341,2
WFC,1.200686,191955615744,3403770112,135925604352,3396315989,0.0289,10.253636,191955615744,0.23956,NaN,0.31666,NaN,78234001408,NaN,0.00984,0.10429,NaN,23631998976,22.0859,5
TSN,1.230709,22246492160,285820992,30811471872,278443855,0.0313,16.496042,22246492160,-0.00013,0.06272,0.0334,2556000000,53091999744,60.548,0.01834,0.00081,866625024,2296000000,None,10
UAL,1.323805,13934340096,328833984,32840042496,326525493,NaN,3.720369,13934340096,0.05277,0.33373,0.13299,7616000000,55635001344,325.423,0.04272,0.32209,-2714625024,5693000192,0.6736,9
SOFI,1.332251,7868768768,1065939968,8319428608,1046757824,NaN,28.392310,7868768768,-0.04836,0.82421,0.02718,NaN,2343481088,54.363,-0.00389,-0.01974,NaN,-2680582912,None,7
CTRA,1.388652,18075248640,739273984,19417765888,727704801,0.035,8.260136,18075248640,0.23558,0.71536,0.23887,3487000064,5565000192,22.743,0.05324,0.10201,794625024,2932000000,None,6
CTVA,1.494725,37561319424,692246976,40249888768,690890196,0.0126,16.343374,37561319424,0.05313,0.43684,0.25736,3214000128,16901000192,18.583,0.02885,0.03415,2345750016,2110000000,1.2756,3